### ISSUE TITLE
Server error on npm start

### ISSUE THREAD

**Issue by angelocorreia27** [storefront-foundation/react-storefront#126]
using node version: 12.14.0
After run this steps
1. npm create react-storefront@^8.0.0 (my-app-name)
2. npm install
3. npm run dev

I get an error:

Server Error
TypeError: Cannot read property 'map' of undefined

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Source
components/NavBar.js (33:35) @ eval

  31 | <NavTab key={tab.as} href={tab.href} as={tab.as} label={tab.text} prefetch="visible">
  32 |   <div style={{ padding: 20 }}>
> 33 |     {tab.subcategories.map(subcategory => (
     |                       ^
  34 |       <Link
  35 |         href={subcategory.href}
  36 |         key={subcategory.as}

**Comment by markbrocato** [comment]
Thank you. There was a bug in the starter app which has now been fixed.  Please recreate your app and try again.

Here's the commit that fixed it:
https://github.com/storefront-foundation/react-storefront-starter-app/commit/9173bd071dd5774f3b71641f28671b9b79322615#diff-fea8f238890d5e576b487ef81a09cfacR34
