### ISSUE TITLE
NavBar & View Cart Error

### ISSUE THREAD

**Issue by bytemedia** [storefront-foundation/react-storefront#128]
I've installed the demo storefront via NPM, and there are two areas of the app that aren't working for me. The first is that the NavBar component generates the following error:

**TypeError: Cannot read property 'map' of undefined**

for line 33 in NavBar.js

> 33 |     {tab.subcategories.map(subcategory => (

When the component is commented out, the front page loads, and I can view products and search as expected.

Also, when a product has been added to the cart, clicking the cart icon generates the following error:

**API resolved without sending a response for /api/cart?__v__=development, this may result in stalled requests.**

With the following on screen message:

**Unhandled Runtime Error
TypeError: Failed to fetch**

I'm on Windows 10, errors are consistent across browsers, with app running locally via Visual Studio.
- Version of React Storefront: 8.15.1

**Comment by bytemedia** [comment]
Sorry, version of Storefront is 8.15.1, not 6.14.7 (NPM version) as shown above.

**Comment by marcosnc08** [comment]
I confirm the errors reported here.

For the error in this line:
`33 | {tab.subcategories.map(subcategory => (`

I changed it to:
`33 | {tab.items.map(subcategory => (`

And works well.

I didn't try to solve the other one yet.

**Comment by scanjko** [comment]
I was getting that error, for Tabs, it is because of diff data structure. You can either aplay fix that @marcosnc08 suggested, which I did as well, but then I checked other versions, and this is fixed in 8.14.1
