### ISSUE TITLE
Getting error while connecting with Salesforce Connector

### ISSUE THREAD

**Issue by asadkhawaja1** [storefront-foundation/react-storefront#137]
# Bug report

## Describe the bug

I have followed all the steps for configuring Salesforce Commerce Cloud Connector but when I start the Application I get bellow error 

Defining routes from exportPathMap
> Using connector react-storefront-salesforce-commerce-cloud-connector
info  - Using external babel configuration from D:\Work\react\react-salesforce-app\.babelrc.js
event - compiled successfully
(node:12828) UnhandledPromiseRejectionWarning: D:\Work\react\react-salesforce-app\node_modules\react-storefront-salesforce-commerce-cloud-connector\index.js:3
export { default as cart } from './cart.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at D:\Work\react\react-salesforce-app\server.js:33:31
(node:12828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:12828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## To Reproduce

Steps mentioned in 
https://github.com/storefront-foundation/salesforce-commerce-cloud-connector

## Expected behavior

connecting with Salesforce Connector

## Screenshots

![error](https://user-images.githubusercontent.com/65772385/94040413-5e045580-fde2-11ea-8257-90c0b6067bf0.jpg)

**Comment by asadkhawaja1** [comment]
process.env file at Root

LEGACY_BACKEND_DOMAIN=https://zzkc-001.sandbox.us01.dx.commercecloud.salesforce.com/on/demandware.store/Sites-RefArch-Site/
LEGACY_BACKEND_HOST_HEADER=https://zzkc-001.sandbox.us01.dx.commercecloud.salesforce.com/on/demandware.store/Sites-RefArch-Site/
CLIENT_ID=477c9069-ff51-4ead-961c-f58ef1adaa04
ORGANIZATION_ID=f_ecom_ZZKC_001
SHORT_CODE=kv7kzm78
SITE_ID=RefArch

**Comment by dijs** [comment]
I am not able to reproduce this error. 

What version of node, react-storefront, xdn, and next are you using?

And how did you initialize the project?

**Comment by asadkhawaja1** [comment]
Node v12.18.3
react-storefront :  8.11.0
next : 9.3.6

I am trying it on my local machine. 

I created a new react storefront, then installed react-storefront-salesforce-commerce-cloud-connector.

After that, I have put a process.env file at Root which looks like this

LEGACY_BACKEND_DOMAIN=https://zzkc-001.sandbox.us01.dx.commercecloud.salesforce.com/on/demandware.store/Sites-RefArch-Site/
LEGACY_BACKEND_HOST_HEADER=https://zzkc-001.sandbox.us01.dx.commercecloud.salesforce.com/on/demandware.store/Sites-RefArch-Site/
CLIENT_ID=477c9069-ff51-4ead-961c-f58ef1adaa04
ORGANIZATION_ID=f_ecom_ZZKC_001
SHORT_CODE=kv7kzm78
SITE_ID=RefArch


I have made changes in next.config.js to change the connector name as mentioned in github steps. 


after all these steps when I try to start it by "npm start" I am getting the above error.

**Comment by dijs** [comment]
Very odd... I just used a Windows machine to test this as well and I am still not getting this error.

What version of Windows are you running?

And it seems like your SFCC permissions are not quite correct for the API. I am not able to create a token.

**Comment by asadkhawaja1** [comment]
change ORGANIZATION_ID to f_ecom_zzkc_001 and you will get the token. 

I am using windows 10. 

I have found that the reason behind this error might be the node version doesn’t support ES6 export syntax.

Can you plz mention what version of node, npm and next are required for this connector??

**Comment by asadkhawaja1** [comment]
https://www.quora.com/What-does-SyntaxError-Unexpected-token-export-mean-when-running-npm-run-server-angular-typescript-npm-syntax-error-unexpected-token-development

**Comment by dijs** [comment]
@asadkhawaja1 I installed the exact version of node you were using. I used nvm-windows to install it.

**Comment by asadkhawaja1** [comment]
@dijs I am now able to start the APP but when I hit http://127.0.0.1:3000/ I get below error in terminal 

Fetching https://kv7kzm78.api.commercecloud.salesforce.com/product/shopper-products/v1/organizations/f_ecom_zzkc_001/categories/root?siteId=RefArch&levels=2
Fetching https://kv7kzm78.api.commercecloud.salesforce.com/product/shopper-products/v1/organizations/f_ecom_zzkc_001/categories/root?siteId=RefArch&levels=2
client status Forbidden
Error: {"type":"https://api.commercecloud.salesforce.com/documentation/error/v1/errors/forbidden","title":"Forbidden","detail":"Your shopper JWT is valid, but you have no permissions to access the resource."}
    at fetchWithToken (D:\Work\Salesforce\Sample Apps\sfcc-connector\.next\server\pages\api.js:918:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async createAppData (D:\Work\Salesforce\Sample Apps\sfcc-connector\.next\server\pages\api.js:1141:7)
    at async Promise.all (index 1)


Could not connect to backend https://zzkc-001.sandbox.us01.dx.commercecloud.salesforce.com/on/demandware.store/Sites-RefArch-Site: getaddrinfo ENOTFOUND
![error](https://user-images.githubusercontent.com/65772385/94576886-4f5ce900-028f-11eb-9497-dd731462db05.jpg)


Can you plz have a look and tell what am I doing wrong? 

Even in postman when I hit for 
https://{{shortCode}}.api.commercecloud.salesforce.com/product/shopper-products/v1/organizations/{{organizationId}}/categories/root?siteId=RefArch&levels=2

I get 

{"type":"https://api.commercecloud.salesforce.com/documentation/error/v1/errors/forbidden","title":"Forbidden","detail":"Your shopper JWT is valid, but you have no permissions to access the resource."}

**Comment by dijs** [comment]
It looks like the page cannot be rendered because the API could not fetch the required data. Most likely the list of categories. Seems like you are still having permissions issues. 

Yes, it is trying to pull categories:

https://kv7kzm78.api.commercecloud.salesforce.com/product/shopper-products/v1/organizations/f_ecom_zzkc_001/categories/root?siteId=RefArch&levels=2

But this is failing because your API token does not have access to them. Please add the needed permissions to your API token and it should work fine.
