### ISSUE TITLE
Broken Slack invitation link across all pages.

### ISSUE THREAD

**Issue by bartkarp** [storefront-foundation/react-storefront#141]
# Bug report

## Describe the bug

I'm unable to join your Slack community, the invitation link is broken in this repo and on your landing page: 
- https://github.com/storefront-foundation/react-storefront/blob/master/README.md#join-the-community-on-slack, 
- https://www.reactstorefront.io

## To Reproduce

1. Go to https://www.reactstorefront.io, scroll to the bottom on the page, and click on "Slack community".
2. Alternatively go to https://github.com/storefront-foundation/react-storefront/ and click on "invitation link".
3. There is no way to sign up, one could only sign in.

## Expected behaviour

Users should be able to sign up for your Slack channel(s).

## System information

Universally broken everywhere.

## Additional context

I realise it's not a bug with react-storefront per se, but had no idea where to report it (normally this would go to Slack I suppose, d'oh) 😞

**Comment by kevhender** [comment]
@bartkarp Thanks for the report. These links should now be fixed.

**Comment by ahmad-reza619** [comment]
It still broken for me
