### ISSUE TITLE
 webpack-clear-require-cache-plugin 0.0.4 is no longer active

### ISSUE THREAD

**Issue by martin-daprotis** [storefront-foundation/react-storefront#145]
# Bug report
Dependency error

## Describe the bug
Hi, I've been experiencing trouble when trying to install the dependencies of package.json. 
webpack-clear-require-cache-plugin 0.0.4 is no longer active, just recently it has been updated to 0.0.5.
It was down for a while.

## To Reproduce

delete del node_modules
delete del package-lock 
execute npm cache clean --force

## Expected behavior

npm ERR! code ETARGET
npm ERR! notarget No matching version found for webpack-clear-require-cache-plugin@0.0.4.

**Comment by dijs** [comment]
This has been updated. Thanks
