### ISSUE TITLE
Unable to start app with npm create

### ISSUE THREAD

**Issue by sankaran85** [storefront-foundation/react-storefront#159]
1. npm create react-storefront@^8.0.0 (my-app-name)
2. then npm start 
 Im getting below error. Please help me out.

**Error: Cannot find module '@material-ui/core/TabScrollButton'**

**Doubt**: Is react storefront is still maintained ?

**Comment by damogongzi** [comment]
the same as me.

**Comment by dijs** [comment]
We updated the @material-ui library which had some breaking changes with import paths. 

I am trying to reproduce this specific case right now.

**Comment by dijs** [comment]
I had forgot to push my updates to the template. The same commands above should work now.
