### ISSUE TITLE
'SERVICE_WORKER' is not recognized as an internal or external command while npm start

### ISSUE THREAD

**Issue by Abd-ksr** [storefront-foundation/react-storefront#160]
> npm create react-storefront@^8.0.0 react-storefront
> npm start

**Getting following Error**

`
> react-storefront@1.0.0 start E:\react-storefront
> SERVICE_WORKER=true xdn run --cache
'SERVICE_WORKER' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-storefront@1.0.0 start: `SERVICE_WORKER=true xdn run --cache`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-storefront@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

Please let me know how to resolve it.

**Comment by dijs** [comment]
What OS are you running on?

**Comment by dijs** [comment]
Never mind. I believe I found the issue and fixed it. Please try creating a new project again.
