### ISSUE TITLE
Error: Invalid hook call. Hooks can only be called inside of the body of a function component

### ISSUE THREAD

**Issue by plamenh** [storefront-foundation/react-storefront#164]
# Bug report

## Describe the bug

Error with useJssStyles...

## To Reproduce

1. npm create react-storefront@latest --yes XXX
2. npm start
3. http://localhost:3000

## Expected behavior

Render as expected.

## Screenshots

<img width="950" alt="Screenshot 2021-01-21 at 9 35 35" src="https://user-images.githubusercontent.com/14073311/105318324-0a591b80-5bcc-11eb-9699-662dbea0d610.png">

## System information

- OS: macOS Apple Silicon
- Version of React Storefront: [@latest (8.17.4)]

## Additional context

M1 Mac

**Comment by plamenh** [comment]
It seems like there is already an issue about this. Closing this one.

**Comment by vishalv971** [comment]
@plamenh Could you share the already open issue number? Thanks in advance
